### ISSUE TITLE
Suddenly appearing asteroids with Streaming 

### ISSUE THREAD

**Issue by Sardaukai** [StalkR/Space-Engineers-Asteroid-Ores#12]
Our player realize a constant streaming signal at screen center.
Then out of nowhere an asteroid appears. This is often nearly in front of the grid of the player.
So the player is not able to stop the grid and crash into.

Our max grid speed at the server is 300m/s
Prozedural density is 0.7

**Comment by StalkR** [comment]
Constant streaming is not normal and what happened is predictable. Do all players see constant streaming? that may be a bigger problem

In general when you see streaming (i.e. without my mod), it's better to wait for the game to finish loading properly before flying around. Same happens on planets, if you start driving without the planet fully loaded, you'll fall into a hole you couldn't see.

Sorry I don't know what to do there, either I load the asteroids but they flicker visually (#9 appear then disappear after client has sync), or in the rare event that you're streaming and arriving to an asteroid, you can crash (#12).

**Comment by Sardaukai** [comment]
I told my player to purge SE for a fresh install.

Another player saw one astroid and the affected did not. 

I will report in some days if we were luky.

**Comment by Sardaukai** [comment]
Problem is still present and we got some additional problems,

Player A connects and play - quit
Player B connects and play - quits
Player A wants to connect -> hang at 50%
Player B wants to connect at the same time -> unable to connect, server does not realize the player

even after server restart player is not able to connect.

I am able to send you the whole log via dm if you want,
is this line something from your mod?

MyVoxelReplicable.OnLoad - isUserCreated:False isFromPrefab:True contentChanged:False data?: True

Both had this entry, I am able to login and haven't that entry
