### ISSUE TITLE
Mod/Plugin seems to be broken

### ISSUE THREAD

**Issue by Sardaukai** [StalkR/Space-Engineers-Asteroid-Ores#4]
Hi, 

great idea of placing asteroid field dynamical.

But I think the mod is broken.

I installed a fresh  empty world at a fresh torch server.
Installed your Plugin.
Copy and pasted the config and the generated AsteroidOres.cfg

Started the game and spawned in a Space Pod (starter ship)

All asteroids are visible but not located at torch or in game admin panel to remove.

If am able to run further tests if you want to.
Maybe you will find a solution to fix this bug.
It would be really great.

Thanks and have a great new year!

**Comment by StalkR** [comment]
> All asteroids are visible but not located at torch or in game admin panel to remove.

That is expected: the plugin relies on vanilla asteroid generation. In vanilla, you also don't see asteroids in torch or admin panel to remove. They are procedurally generated, appearing on both client and server on demand, but do not really exist as a voxel file until the asteroid is modified (i.e. the voxel map is modified). At this point, you'll see the asteroid appear as a file on the server save and in the admin panel.

I hope this helps better understand how the plugin works.

**Comment by Sardaukai** [comment]
So a player see all asteroids and have to check everyone if it is a real one with ores by crashing in or fly threw?

**Comment by StalkR** [comment]
No, a player will only see the asteroids that exist. The ones that have been removed by the server, and the client, do not appear, as you would expect.

(Note: careful flying around as admin with spectator mode, it messes up object tracking, cf. #3)

**Comment by Sardaukai** [comment]
Ok than this is the bug

Fresh server, plugin configured, empty game, spawn with space pod.

Player see asteorides and can fly threw. This asteorides does not appear at files too

Edit: I never used spectator at this new world

Edit2: Game or server restart does not fix the problem

**Comment by StalkR** [comment]
Ok then sorry I don't know, I agree it's not supposed to do that. For the record, it works well on other servers.

Can you share your config?

**Comment by StalkR** [comment]
To confirm, did you add the companion mod mentioned in the README to your server config? https://steamcommunity.com/workshop/filedetails/?id=3037359638

That's what synchronizes asteroids on clients, so if you don't have it, yes it's not gonna work.

**Comment by Sardaukai** [comment]
Does it add the mod not automatically? 


... if not this will be the solution ....

**Comment by StalkR** [comment]
No it doesn't it doesn't add the mod automatically, but I agree it would be nice, filed #5 to do it. Until then add the mod yourself.

Glad we found what was your issue and resolved it!

**Comment by Sardaukai** [comment]
Sorry, its like rtfm.... It works :)

What prozedural density would you recommend?

 I tested a bit and 0.35 seems to be really low density.

**Comment by StalkR** [comment]
Procedural density depends on your asteroid ores configuration.

To help you find the right setting, remember how the plugin works: it uses vanilla asteroid generation, then deletes the asteroid with any ore you don't want. And the game likes to create asteroid with two ores, rarely only one. So the more ores you restrict in the configuration, the more asteroids are deleted, making space feel very empty. With more than 3-5 ores removed I recommend 0.99 density as I find it's still quite empty, especially if you're also using small shapes like an asteroid ring of small height. To increase density further, you need to look into modding the vanilla asteroid generation, something I want to play with myself but haven't yet.

**Comment by StalkR** [comment]
added some docs thanks to your feedback and our discussion https://github.com/StalkR/Space-Engineers-Asteroid-Ores/commit/1126896f37e54d4edd1833e329b49777e7974d68
