### ISSUE TITLE
plugin should add mod automatically 

### ISSUE THREAD

**Issue by StalkR** [StalkR/Space-Engineers-Asteroid-Ores#5]
Some server admins forget to add it, look into having the plugin add it automatically.

**Comment by Sardaukai** [comment]
Is it possible to set mod to public again?
Otherwise torch can not find the mod and does not start.
Or is there a setting for non anonymous login?

Edit:
Maybe the mod loads, but it does not resolve the name at gui...

**Comment by StalkR** [comment]
The mod is not hidden, just unlisted (https://steamcommunity.com/workshop/filedetails/?id=3037359638) so it doesn't appear in searches or my profile because it's just a companion mod, the mod doesn't do anything by itself, it needs the plugin.

I don't know about Torch not resolving the name in the gui, that would be something to report with Torch directly
