### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by Sardaukai** [StalkR/Space-Engineers-Asteroid-Ores#6]
I have got a small idea for better densities.

If we were able to use a value to delete every second or third correct spawned asteorid we would be able to make denser fields or just a few ones.

Game density could be 10

Field density regulates the field

**Comment by StalkR** [comment]
Unfortunately the problem is that density is too low, not that it's too high and we're looking for ways to delete more asteroids (that's easy indeed, can be done as you described).

**Comment by Sardaukai** [comment]
Oh, is density capped?

**Comment by StalkR** [comment]
Yep at 0.999 it still feels empty, so if you remove asteroids because of ores, it feels even more empty.

But you can mod the asteroid generator parameters to increase further, cf. https://github.com/StalkR/Space-Engineers-Asteroid-Ores?tab=readme-ov-file#asteroid-fields-feel-too-empty
