### ISSUE TITLE
Boulders are also affected

### ISSUE THREAD

**Issue by Sardaukai** [StalkR/Space-Engineers-Asteroid-Ores#8]
Title says all.
Keep in mind to setup rules for planets.

Is it possible to write a planet rule instead of xyz coord andcradius?

**Comment by StalkR** [comment]
> Boulders are also affected

You mean they are deleted when they shouldn't? I can look into it to exclude them.

> Is it possible to write a planet rule instead of xyz coord andcradius?

No, that is not implemented. I'm happy with the coordinates and radius parameters currently, as it's rare to change planet coordinates so it's only a mild annoyance to update coordinates when that happens. You can fork and implement it yourself if you'd like.

**Comment by StalkR** [comment]
As part of the latest rework, it's now specifically filtering on "Asteroid" so that should exclude boulders now.

Thanks again for the report, I'll consider this fixed but reopen if you still have issues.
